apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  ports:
  - protocol: TCP
    port: 5672 # service port
    targetPort: 5672 # container port
  clusterIP: None # this is called as headless service
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  ports:
  - protocol: TCP
    port: 5672 # service port
    targetPort: 5672 # container port
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  serviceName: "rabbitmq-headless"
  replicas: 1
  template:
    metadata:
      labels:
       project: roboshop
       tier: db
       component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        volumeMounts:
        - name: rabbitmq
          mountPath: /data
  # pvc
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi